### ISSUE TITLE
Syntax highlighting broken in storybook

### ISSUE THREAD

**Issue by gesquinca** [ConsenSys/rimble-ui#244]
**Describe the bug**
Syntax highlighting in storybook is not displaying correctly.

**To Reproduce**
1. Go to 'https://consensys.github.io/rimble-ui/?path=/story/components-text--documentation'
2. Scroll down to any code blocks

**Expected behavior**
Opening and closing tags should be the same color.

**Screenshots**
![Uploading Screen Shot 2019-04-12 at 3.05.27 PM.png…]()

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 73.0.3683.86 (Official Build) (64-bit)

**Comment by MikeLockz** [comment]
PrismJS syntax for .jsx requires that the markup get wrapped in parens () in order to highlight matching tags the same color. 

If we are only showing markup for the docs, we can use `language-html` for all the snippets. If there are any examples that are full-blown .jsx with class declaration then we should pass in a syntax prop like `syntax="language-jsx"`.

**Comment by gesquinca** [comment]
I'm still seeing syntax highlighting showing up like this: 

<img width="799" alt="Screen Shot 2019-04-16 at 3 45 29 PM" src="https://user-images.githubusercontent.com/1707044/56214728-b5838b00-605e-11e9-85dc-bb806b77f6eb.png">
