### ISSUE TITLE
Missing styled-components dependancy for rimble-ui

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/rimble-ui#356]
**Describe the issue**
**rimble-ui** miss _styled-components_ dependancy.
1. Installed **rimble-ui** with `yarn add rimble-ui`.
2. `yarn start` refuse to compile and mention missing _styled-components_ module.
3. Fix compilation by using `yarn add styled-components`

Seems related to #187 

**Rimble UI Version**
- 0.9.7 (latest)

**Comment by gesquinca** [comment]
Hey @Magicking, thanks for submitting. In order to prevent errors with applications already using `styled-components`, we declare `styled-components` as a peer dependency of `rimble-ui`. Our installation instructions indicate you should install both libraries in your app for everything to work. If you see any installation instructions missing this step, please let us know. 

https://github.com/ConsenSys/rimble-ui#install

https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
